import discord
from discord.commands import Option
from discord.ui import Button, View

intents = discord.Intents.all()

bot = discord.Bot(intents=intents)

AIRPORTS = ["IRFD (Greater Rockford/New York)", "IPPH (Perth Intl/Paris)", "IZOL (Izonari/Madrid)",                      #HERE YOU CAN ADD AIRPORTS, PUT THEM
            "Saint Barthelemy (soon ?)", "ITKO (Tokyo Intl./Rome)", "ILAR (London/Lacarna)", "IPAP (Athens/Pahos)"]      #SUCH AS: ["airport 1", "airport 2"]
VISIBILITY = ["Ask tower", "5nm", "10nm", "35nm", "40nm", "45nm", "50nm", "55nm", "60nm", "70+nm"]                       #ALL VALUES CAN BE EDITED

TAXI_SPD = ["Ask tower", "5", "10", "15", "20", "25", "30", "35", "N/A"]

international_alphabet = ["Alpha", "Bravo", "Charlie", "Delta", "Echo", "Foxtrot", "Golf", "Hotel",
                          "India", "Juliet", "Kilo", "Lima", "Mike", "November", "Oscar", "Papa", "Quebec", "Romeo",
                          "Sierra",
                          "Tango", "Uniform", "Victor", "Whiskey", "X-ray", "Yankee", "Zulu"]
international_letter = 0


def atis_info():
    global international_letter
    if international_letter >= 26:
        international_letter = 0
    return international_alphabet[international_letter]
    international_letter += 1


@bot.event
async def on_ready():
    print(f"{bot.user} is ready and online")

@bot.slash_command(name="atis", description="Used to create an ATIS")
async def atis(ctx, airport: Option(str, "Choose an airport", choices=AIRPORTS, required=True),
               controler_callsign: Option(str, "Choose controler callsign (between 5 and 20 chars)", min_lenght=5,
                                          max_lenght=20, required=True),
               weather: Option(str, "Choose the weather (max 500 chars)", required=True, max_length=500),
               visibility: Option(str, "Choose visibility", choices=VISIBILITY, required=True),
               qnh: Option(float, "Choose QNH (between 800hPa and 1200hPa", max_value=1200, min_value=800,
                           required=True),
               max_taxi_spd: Option(str, "Choose max taxi speed", choices=TAXI_SPD, required=True),
               min_taxi_spd: Option(str, "Choose min taxi speed", choices=TAXI_SPD, required=True),
               departure_rw: Option(str, "Choose departures runway(s) (between 2 and 12chars).",
                                    min_length=2, max_length=12, required=True),
               arrival_rw: Option(str,
                                  "Choose arrival runway(s). if multiple runways please separate them with /, (between 2 and 12chars)",
                                  min_length=2, max_length=12, required=True),
               max_aircraft_size: Option(str,
                                         "Choose max aircraft size in metters. let clear for none (between 1 and 3chars)",
                                         min_length=1, max_length=3, required=False, default="N/A"),
               notams: Option(str, "Enter airport NOTAMS let clear for none (max 500 chars).", max_length=500,
                              required=False, default="N/A")):
    atis_letter = atis_info()
    embed = discord.Embed(title=f"Controler callsign: {controler_callsign}", color=0x1e029d)
    embed.set_author(name=f"{airport} ATIS Information {atis_letter}",
                     icon_url="https://tiermaker.com/images/templates/5529221598031147.png")
    embed.set_thumbnail(url="https://cdn.discordapp.com/attachments/1047458824644206632/1048274283991932958/image.png")
    embed.add_field(name="**Weather:**", value=weather, inline=False)
    embed.add_field(name="**Winds:**", value="ask tower", inline=False)
    embed.add_field(name="**Visibility:**", value=visibility, inline=False)
    embed.add_field(name="**QNH:**", value=qnh, inline=False)
    embed.add_field(name="**Max taxi speed:**", value=max_taxi_spd, inline=False)
    embed.add_field(name="**max taxi speed:**", value=min_taxi_spd, inline=False)
    embed.add_field(name="**Arrival runway(s):**", value=arrival_rw, inline=False)
    embed.add_field(name="**Departure runway(s):**", value=departure_rw, inline=False)
    embed.add_field(name="*Max aircraft size:*", value=max_aircraft_size, inline=False)
    embed.add_field(name="*NOTAMS:*", value=notams, inline=False)
    embed.add_field(name=f"**End of atis information {atis_letter}**",
                    value=f"*ATIS generated by {ctx.author.mention}*", inline=False)
    embed.set_footer(text="Air France ATIS - this message is for RP purposes only, values may be not accurate.")
    await ctx.respond(embed=embed)


bot.run("YOUR BOT TOKEN HERE !!")
